export const skills = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Tailwind",
  "Nextjs",
  "Nodejs",
  "MongoDB",
  "Mongoose",
  "Express",
  "MySQL",
  "Firebase Auth",
  "Vercel",
  "Netlify",
  "Zustand",
  "Redux",
  "React Query",
  "Git",
  "GitHib",
  "Figma",
  "Framer Motion",
  "Java",
  "Cpp",
  "C",
  "Python",
  "Machine Learning",
  "Android App Development",
  "Apple App Development",
  "GSAP",
  "Web Development",
  "SDLC",
  "Data Structures and Algorithms",
  "Object Oriented Programming",
  "UI/UX",
  "Communication",
];

export const jobRoles = [
  "Software Developer",
  "React Developer",
  "Nextjs Developer",
  "Web Developer",
  "Data Scientist",
  "Network Engineer",
  "Database Administrator",
  "System Administrator",
  "DevOps Engineer",
  "Machine Learning Engineer",
  "Cybersecurity Analyst",
  "UI/UX Designer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Mobile App Developer",
  "Cloud Solutions Architect",
  "Software Engineer",
  "Systems Analyst",
  "Quality Assurance Engineer",
  "IT Consultant",
  "Network Security Engineer",
];

export const softwareCompanies = [
  "CodeCrafters Tech",
  "InnovateSoft Solutions",
  "ByteMinds Innovations",
  "LogicNest Systems",
  "SynthCode Technologies",
  "BinaryBeam Software",
  "TechSprint Innovations",
  "QuantumLogic Software",
];

export const uniInstitutionNames = [
  "University of Example",
  "Tech Institute",
  "Science University",
  "Art College",
  "Business School",
];
export const degrees = [
  "Bachelor of Science",
  "Master of Engineering",
  "Bachelor of Arts",
  "Master of Fine Arts",
  "Bachelor of Business Administration",
];
export const fieldsOfStudy = [
  "Computer Science",
  "Software Engineering",
  "Mathematics",
  "Painting",
  "Finance",
];

export const courseInstitutionNames = [
  "Programming Academy",
  "Data Science Institute",
  "Design School",
  "Business Training Center",
  "Language School",
];
export const courseTitles = [
  "Web Development Bootcamp",
  "Machine Learning Fundamentals",
  "Graphic Design Workshop",
  "Project Management Certification",
  "Spanish Language Intensive Course",
];
