-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "institutionName" DROP NOT NULL;
ALTER TABLE "Course" ALTER COLUMN "institutionName" DROP DEFAULT;
ALTER TABLE "Course" ALTER COLUMN "courseName" DROP NOT NULL;
ALTER TABLE "Course" ALTER COLUMN "courseName" DROP DEFAULT;
ALTER TABLE "Course" ALTER COLUMN "startDate" DROP NOT NULL;
ALTER TABLE "Course" ALTER COLUMN "startDate" DROP DEFAULT;
ALTER TABLE "Course" ALTER COLUMN "finishDate" DROP NOT NULL;
ALTER TABLE "Course" ALTER COLUMN "finishDate" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "institutionName" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "degree" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "degree" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "fieldOfStudy" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "fieldOfStudy" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "gpa" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "gpa" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "maxGpa" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "maxGpa" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "startDate" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "startDate" DROP DEFAULT;
ALTER TABLE "Education" ALTER COLUMN "finishDate" DROP NOT NULL;
ALTER TABLE "Education" ALTER COLUMN "finishDate" DROP DEFAULT;
